
version: '3'

dotenv: [".env", ".env.build", ".env.production"]

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  backup:
      - cp -rf dist/renderer /run/media/botvid/LACIE\ MUSIC/latest
  increment:
      - sh ./build.sh
  prebuild:
    slient: true
    cmds:
      - yarn run prebuild
  nw:
    env:
      VITE_STTYLUS_MODE: desktop
      VITE_STTYLUS_LOCAL_BACKEND: http://localhost
      VITE_STTYLUS_BACKEND: http://localhost
    cmds:
      - task: increment
      - echo "Building $STTYLUS_BUILD ..."
      - cp packages/loader/manifest.json dist/renderer/package.json
      - cp packages/loader/index.js dist/renderer/index.js
      - task: prebuild
      - task: local
      - task: consumer
      - cp -r dist/renderer/* /tmp/latest/
    silent: false
  nw:debug:
    env:
      VITE_STTYLUS_MODE: desktop
    cmds:
      - echo "Debug $STTYLUS_BUILD ..."
      - yarn run prebuild
      - cp packages/loader/index.js dist/renderer/index.js
      - ../nw/nw ./dist/renderer/ 
    silent: false
  nw:run:
    env:
      VITE_STTYLUS_MODE: desktop
      VITE_STTYLUS_LOCAL_BACKEND: http://localhost
      VITE_STTYLUS_BACKEND: http://localhost
    cmds:
      - echo "Running build $STTYLUS_BUILD ..."
      - cp packages/loader/index.js dist/renderer/index.js
      - cp packages/loader/update.html dist/renderer/update.html
      - ../nw/nw ./dist/renderer/ 
    silent: false
  debug:
    env:
      VITE_STTYLUS_MODE: desktop
      VITE_STTYLUS_BACKEND: http://localhost:14411
      VITE_STTYLUS_LOCAL_BACKEND: http://localhost:14411
      VITE_STTYLUS_BACKEND: http://localhost
    cmds:
      - echo "Build and run STTylus on vite dev server..."
      - yarn debug
    silent: true
  debug:webapp:
    env:
      VITE_STTYLUS_LOCAL_BACKEND: http://localhost:14411
      VITE_STTYLUS_BACKEND: http://localhost:14411
      VITE_STTYLUS_MODE: api
      VITE_STTYLUS_DEBUG: true
    cmds:
      - echo "[ run as webapp ]"
      - yarn debug
    silent: true
  debug:backend:
    env:
      STTYLUS_PORT: 14411
    cmds:
      - cp ../tools/sttylus.db ./offline
      - (cd packages/backend && go build . && mv webapp ../../offline/backend)
      - sudo setcap CAP_NET_BIND_SERVICE=+eip ./offline/backend 
      - (cd ./offline && ./backend)
      - rm ./offline/sttylus.db
    silent: true
  local:
    env:
      STTYLUS_VERSION: 0.0.0
      STTYLUS_MODE: desktop
    cmds:
      - echo "Building backend.exe for desktop app"
      - (cd packages/backend && go build . && mv webapp ../../dist/renderer/backend.exe)
  local:win:
    env:
      GOOS: windows
      GOARCH: amd64
      VITE_STTYLUS_MODE: desktop
      VITE_STTYLUS_LOCAL_BACKEND: http://localhost
      VITE_STTYLUS_BACKEND: http://localhost
    cmds:
      - rm -rf ./dist/renderer/assets/*
      - (cd packages/backend && go build -o ../../dist/renderer/backend.exe)
      - yarn run prebuild
  webapp:
    env:
      STTYLUS_VERSION: 0.8.2
      STTYLUS_MODE: webapp
      VITE_STTYLUS_MODE: api
      VITE_STTYLUS_BACKEND: https://sttylus.se
    cmds:
      - echo "Building STTylus webapp $STTYLUS_VERSION"
      - rm -rf ./dist/renderer/assets/*
    silent: true
  webapp:test:
    cmds:
      - task: webapp
      - yarn run debug
    silent: true
  webapp:build:
    cmds:
      - task: webapp
      - yarn run prebuild
    silent: true
  deploy:
    cmds:
      - task: webapp:build
      - task: consumer
      - sh ./deploy_backup.sh
      - sh ./deploy_backend.sh
      - sh ./deploy_webapp.sh
      - sh ./deploy_consumer.sh
  deploy:webapp:
    cmds:
      - task: webapp:build
      - sh ./deploy_webapp.sh
  deploy:consumer:
    cmds:
      - task: consumer
      - sh ./deploy_consumer.sh
  router:
    cmds:
      #- task: prebuild
      - xdg-open http://localhost:8000/
      - (cd dist/renderer && python -m http.server)
  consumer:
    cmds:
      - echo "Building consumer"
      - yarn run build:consumer
      - mkdir -p dist/renderer/public
      - rm -rf dist/renderer/public/* packages/backend/public/*
      - cp -rf dist/consumer/* dist/renderer/public/
      - cp -rf dist/consumer/* packages/backend/public/
  build:
    env: 
      VITE_STTYLUS_MODE: desktop
      VITE_STTYLUS_BACKEND: http://localhost:14410
    cmds:
      - task: local
      - echo "Building desktop app pointing to $VITE_STTYLUS_BACKEND"
      - yarn run build
  
